# https://embarkstudios.github.io/cargo-deny/

targets = [
    { triple = "aarch64-apple-darwin" },
    { triple = "aarch64-linux-android" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]


[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
ignore = []


[bans]
multiple-versions = "deny"
wildcards = "allow" # at least until https://github.com/EmbarkStudios/cargo-deny/issues/241 is fixed
deny = []
skip = [
    { name = "windows-sys" }, # console and terminal_size both depend on an old version
]
skip-tree = [
	{ name = "syn" }, # tokio-macros and serde_derive use v2 syn
	{ name = "base64" }, # swc_ecma_transforms_* use v0.13 base64
]


[licenses]
unlicensed = "allow"
allow-osi-fsf-free = "either"
copyleft = "allow"
