packages:
  - "examples/*"
  - "client"
  - "crates/binding"
  - "packages/*"
  - "e2e/fixtures/module-federation.*"
  - "e2e/fixtures.umi/react-16"
  - "e2e/fixtures.umi/config.less.plugins"
  - "e2e/fixtures.umi/stable-hash"
