// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"ant-design-icons":{"path":"ant-design-icons","id":"ant-design-icons"},"ant-design-pro":{"path":"ant-design-pro","id":"ant-design-pro"},"monaco-editor":{"path":"monaco-editor","id":"monaco-editor"},"react-query":{"path":"react-query","id":"react-query"},"todos":{"path":"todos","id":"todos"},"home":{"path":"home","id":"home"}} as const;
  return {
    routes,
    routeComponents: {
'ant-design-icons': React.lazy(() => import(/* webpackChunkName: "src__pages__ant-design-icons" */'../../../src/pages/ant-design-icons.tsx')),
'ant-design-pro': React.lazy(() => import(/* webpackChunkName: "src__pages__ant-design-pro" */'../../../src/pages/ant-design-pro.tsx')),
'monaco-editor': React.lazy(() => import(/* webpackChunkName: "src__pages__monaco-editor" */'../../../src/pages/monaco-editor.tsx')),
'react-query': React.lazy(() => import(/* webpackChunkName: "src__pages__react-query" */'../../../src/pages/react-query.tsx')),
'todos': React.lazy(() => import(/* webpackChunkName: "src__pages__todos" */'../../../src/pages/todos.tsx')),
'home': React.lazy(() => import(/* webpackChunkName: "src__pages__home" */'../../../src/pages/home.tsx')),
},
  };
}
