[package]
name    = "mako_plugin_macro"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
proc-macro2 = "1"
quote       = "1"
serde_json  = { workspace = true }
syn         = { version = "2", features = ["full"] }

[lib]
proc-macro = true
