[build]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-Zthreads=8",
  "-Csymbol-mangling-version=v0",
]
rustdocflags = []

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-C",
  "target-feature=+crt-static",
]

[target.i686-pc-windows-msvc]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-C",
  "target-feature=+crt-static",
]

[target.aarch64-pc-windows-msvc]
linker = "rust-lld"

[target.'cfg(target_os = "macos")']
linker = "rust-lld"

[target.'cfg(all(target_os = "linux", target_env = "gnu"))']
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-Zthreads=8",
  "-Zunstable-options",
  "-Csymbol-mangling-version=v0",
  "-Clinker-flavor=gnu-lld-cc",
  "-Clink-self-contained=+linker",
]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-Csymbol-mangling-version=v0",
  "-Ctarget-feature=-crt-static",
  "-Clink-arg=-lgcc",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-Zthreads=8",
  "-Csymbol-mangling-version=v0",
  "-Ctarget-feature=-crt-static",
]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
