import React from 'react';
console.log(process.env.NODE_ENV);
console.log(AAA);
console.log(BBB);
console.log(CCC);
console.log(DDD);
console.log(EEE);
console.log(FFF);
console.log(GGG);
console.log('process.env', HHH);
export default () => <div>1</div>;
