#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# for rust code
cargo lintfix
cargo fmt
# for js code
npm run rome:format

# only add staged files though cargo fmt all projects
git add $(git diff --name-only --cached --diff-filter=AM)

