#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# for rust code
cargo lintfix
cargo fmt
# for js code
npm run biome:format

# for toml files
npx taplo format

# only add staged files though cargo fmt all projects
git diff --name-only --cached --diff-filter=AM -z | xargs -0 git add
