#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# for rust code
cargo lint
cargo fmt --all --check
# only add staged files though cargo fmt all projects
git add $(git diff --name-only --cached --diff-filter=AM)

# for js code
npx --no-install lint-staged
