name: Rust-Benchmark

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark with antd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain update nightly && rustup default nightly

      - name: Setup cargo cache
        uses: actions/cache@v3
        with:
          # ref: https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-store-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup benchmark data
        uses: actions/cache@v3
        with:
          # ref: https://github.com/benchmark-action/github-action-benchmark#minimal-setup
          path: ./benchmark-data
          key: ${{ runner.os }}-benchmark

      - name: Run benchmark
        run: cargo bench --bench with_antd -- --output-format bencher | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '150%'
          comment-always: true
          external-data-json-path: ./benchmark-data/prev.json

