name: Rust-Benchmark

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark with antd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run: cargo bench mako_with_antd | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '150%'
          comment-always: true
